/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Calisan;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Database;

/**
 *
 * @author Mert
 */
public class CalisanEkrani extends javax.swing.JDialog {

    private DefaultTableModel model;
    private Database db;
    Statement statement;
    ResultSet resultSet;
    Calisan calisanListele = new Calisan();

    /**
     * Creates new form CalisanEkrani
     */
    public CalisanEkrani(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        model = (DefaultTableModel) calisanTable.getModel();
        db = new Database();
        calisanlariGoruntule();
    }

    public ArrayList<Calisan> calisanlariListele() {
        ArrayList<Calisan> calisanList = new ArrayList<>();
        try {
            db.baglan();
            String sorgu = "SELECT * FROM calisanlar";
            statement = db.con.createStatement();
            resultSet = statement.executeQuery(sorgu);

            while (resultSet.next()) {
                int id = resultSet.getInt("id");
                String ad = resultSet.getString("ad");
                String soyad = resultSet.getString("soyad");
                String departman = resultSet.getString("departman");
                int maas = resultSet.getInt("maas");
                calisanList.add(new Calisan(id, ad, soyad, departman, maas));
            }
            return calisanList;
        } catch (SQLException e) {
            System.out.println("Hata \n" + e);
            return null;
        }
    }

    public void calisanlariGoruntule() {
        model.setRowCount(0);

        ArrayList<Calisan> calisanlar = new ArrayList<>();

        calisanlar = calisanlariListele();

        if (calisanlar != null) {
            for (Calisan calisan : calisanlar) {
                Object[] eklenecek = {calisan.getId(), calisan.getAd(), calisan.getSoyad(), calisan.getDepartman(), calisan.getMaas()};
                model.addRow(eklenecek);
            }
        }
    }

    public void calisanAra(String ara) {
        TableRowSorter<DefaultTableModel> tableRowSorter = new TableRowSorter<>(model);
        calisanTable.setRowSorter(tableRowSorter);
        tableRowSorter.setRowFilter(RowFilter.regexFilter(ara));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        calisanTable = new javax.swing.JTable();
        aramaCubuguTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        adTextField = new javax.swing.JTextField();
        soyadTextField = new javax.swing.JTextField();
        departmanTextField = new javax.swing.JTextField();
        maasTextField = new javax.swing.JTextField();
        mesajYazisiLabel = new javax.swing.JLabel();
        calisanEkleButton = new javax.swing.JButton();
        calisanGuncelleButton = new javax.swing.JButton();
        calisanSilButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Çalışan Ekranı");

        calisanTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Ad", "Soyad", "Departman", "Maaş"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        calisanTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calisanTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(calisanTable);
        if (calisanTable.getColumnModel().getColumnCount() > 0) {
            calisanTable.getColumnModel().getColumn(0).setResizable(false);
            calisanTable.getColumnModel().getColumn(1).setResizable(false);
            calisanTable.getColumnModel().getColumn(2).setResizable(false);
            calisanTable.getColumnModel().getColumn(3).setResizable(false);
            calisanTable.getColumnModel().getColumn(4).setResizable(false);
        }

        aramaCubuguTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        aramaCubuguTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                aramaCubuguTextFieldKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Ad : ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Soyad : ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Departman : ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Maaş : ");

        adTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        soyadTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        departmanTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        maasTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        mesajYazisiLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mesajYazisiLabel.setForeground(new java.awt.Color(255, 0, 51));

        calisanEkleButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        calisanEkleButton.setText("Yeni Çalışan Ekle");
        calisanEkleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calisanEkleButtonActionPerformed(evt);
            }
        });

        calisanGuncelleButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        calisanGuncelleButton.setText("Çalışan Güncelle");
        calisanGuncelleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calisanGuncelleButtonActionPerformed(evt);
            }
        });

        calisanSilButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        calisanSilButton.setText("Çalışan Sil");
        calisanSilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calisanSilButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(aramaCubuguTextField)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(adTextField)
                            .addComponent(soyadTextField)
                            .addComponent(departmanTextField)
                            .addComponent(maasTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                        .addGap(191, 191, 191)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(calisanEkleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(calisanGuncelleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(calisanSilButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(mesajYazisiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(aramaCubuguTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(adTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(calisanEkleButton)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(soyadTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calisanGuncelleButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(departmanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calisanSilButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(maasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(mesajYazisiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void aramaCubuguTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aramaCubuguTextFieldKeyReleased
        String ara = aramaCubuguTextField.getText();
        calisanAra(ara);
    }//GEN-LAST:event_aramaCubuguTextFieldKeyReleased

    private void calisanEkleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calisanEkleButtonActionPerformed
        mesajYazisiLabel.setText("");
        String ad = adTextField.getText();
        String soyad = soyadTextField.getText();
        String departman = departmanTextField.getText();
        int maas = Integer.valueOf(maasTextField.getText());

        calisanListele.calisanEkle(ad, soyad, departman, maas);

        calisanlariGoruntule();

        mesajYazisiLabel.setText("Yeni çalışan başarıyla eklendi.");
    }//GEN-LAST:event_calisanEkleButtonActionPerformed

    private void calisanTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calisanTableMouseClicked
        int selectedRow = calisanTable.getSelectedRow();
        adTextField.setText(model.getValueAt(selectedRow, 1).toString());
        soyadTextField.setText(model.getValueAt(selectedRow, 2).toString());
        departmanTextField.setText(model.getValueAt(selectedRow, 3).toString());
        maasTextField.setText(model.getValueAt(selectedRow, 4).toString());
    }//GEN-LAST:event_calisanTableMouseClicked

    private void calisanGuncelleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calisanGuncelleButtonActionPerformed
        mesajYazisiLabel.setText("");
        String ad = adTextField.getText();
        String soyad = soyadTextField.getText();
        String departman = departmanTextField.getText();
        int maas = Integer.valueOf(maasTextField.getText());
        int selectedRow = calisanTable.getSelectedRow();

        if (selectedRow == -1) {
            if (model.getRowCount() == 0) {
                mesajYazisiLabel.setText("Çalışanlar tablosu şu an boş.");
            } else {
                mesajYazisiLabel.setText("Lütfen güncellenecek bir çalışan seçin.");
            }
        } else {
            int id = (int) model.getValueAt(selectedRow, 0);
            calisanListele.calisanGuncelle(id, ad, soyad, departman, maas);
            calisanlariGoruntule();
            mesajYazisiLabel.setText("Çalışan başarıyla güncellendi.");
        }
    }//GEN-LAST:event_calisanGuncelleButtonActionPerformed

    private void calisanSilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calisanSilButtonActionPerformed
        mesajYazisiLabel.setText("");
        int selectedRow = calisanTable.getSelectedRow();

        if (selectedRow == -1) {
            if (model.getRowCount() == 0) {
                mesajYazisiLabel.setText("Çalışanlar tablosu şu an boş.");
            } else {
                mesajYazisiLabel.setText("Lütfen silinecek bir çalışan seçin.");
            }
        } else {
            int id = (int) model.getValueAt(selectedRow, 0);
            calisanListele.calisanSil(id);
            calisanlariGoruntule();
            mesajYazisiLabel.setText("Çalışan başarıyla silindi.");
        }
    }//GEN-LAST:event_calisanSilButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalisanEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalisanEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalisanEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalisanEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CalisanEkrani dialog = new CalisanEkrani(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adTextField;
    private javax.swing.JTextField aramaCubuguTextField;
    private javax.swing.JButton calisanEkleButton;
    private javax.swing.JButton calisanGuncelleButton;
    private javax.swing.JButton calisanSilButton;
    private javax.swing.JTable calisanTable;
    private javax.swing.JTextField departmanTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField maasTextField;
    private javax.swing.JLabel mesajYazisiLabel;
    private javax.swing.JTextField soyadTextField;
    // End of variables declaration//GEN-END:variables
}
